#include "pauli_bench/resampling_bfs.hpp"
#include <algorithm>
#include <chrono>
#include <cmath>
#include <complex>
#include <random>
#include <stdexcept>
#include <unordered_map>
#include <utility>
#include <vector>
namespace pbv1 {
namespace {
using Map=std::unordered_map<Pauli,double,PauliHash>;
using Clock=std::chrono::steady_clock;
int label(const Pauli&p,int q){return (((p.x>>q)&1)?1:0)|(((p.z>>q)&1)?2:0);}
void set_label(Pauli&p,int q,int l){auto m=1ULL<<q;p.x=(p.x&~m)|((l&1)?m:0);p.z=(p.z&~m)|((l&2)?m:0);}
void apply_h(Pauli&p,double&w,int q){int l=label(p,q);if(l==1)set_label(p,q,2);else if(l==2)set_label(p,q,1);else if(l==3)w=-w;}
void apply_s(Pauli&p,double&w,int q){int l=label(p,q);if(l==1){set_label(p,q,3);w=-w;}else if(l==3)set_label(p,q,1);}
struct CnotEntry{int a=0,b=0,s=1;};
const CnotEntry& cnot_entry(int a,int b){
 static CnotEntry table[4][4]; static bool init=false;
 if(!init){using C=std::complex<double>;C I[2][2]={{1,0},{0,1}},X[2][2]={{0,1},{1,0}},Z[2][2]={{1,0},{0,-1}},Y[2][2]={{0,C(0,-1)},{C(0,1),0}};C(*P[4])[2]={I,X,Z,Y};C U[4][4]={{1,0,0,0},{0,1,0,0},{0,0,0,1},{0,0,1,0}};for(int a0=0;a0<4;++a0)for(int b0=0;b0<4;++b0){C A[4][4]{};for(int i=0;i<2;++i)for(int j=0;j<2;++j)for(int k=0;k<2;++k)for(int l=0;l<2;++l)A[2*i+k][2*j+l]=P[a0][i][j]*P[b0][k][l];C B[4][4]{};for(int i=0;i<4;++i)for(int j=0;j<4;++j)for(int k=0;k<4;++k)for(int m=0;m<4;++m)B[i][j]+=std::conj(U[k][i])*A[k][m]*U[m][j];for(int ao=0;ao<4;++ao)for(int bo=0;bo<4;++bo){C tr=0.;for(int i=0;i<2;++i)for(int j=0;j<2;++j)for(int k=0;k<2;++k)for(int l=0;l<2;++l)tr+=std::conj(P[ao][i][j]*P[bo][k][l])*B[2*i+k][2*j+l];tr/=4.;if(std::abs(std::abs(tr.real())-1)<1e-9)table[a0][b0]={ao,bo,tr.real()>0?1:-1};}}init=true;}
 return table[a][b];
}
void apply_cnot(Pauli&p,double&w,int c,int t){auto e=cnot_entry(label(p,c),label(p,t));set_label(p,c,e.a);set_label(p,t,e.b);w*=e.s;}
void advance(const Map&cur,Map&next,const Gate&g){next.clear();next.reserve(cur.size()*2+1);for(const auto&[p0,w0]:cur){if(g.kind==GateKind::RZ){int l=label(p0,g.q0);if(l==1||l==3){double co=std::cos(g.theta),si=std::sin(g.theta);Pauli p2=p0;next[p0]+=w0*co;if(l==1){set_label(p2,g.q0,3);next[p2]+=w0*(-si);}else{set_label(p2,g.q0,1);next[p2]+=w0*si;}}else next[p0]+=w0;}else if(g.kind==GateKind::DEPOL){double w=w0;if(label(p0,g.q0)!=0)w*=1.0-g.theta;next[p0]+=w;}else{Pauli p=p0;double w=w0;if(g.kind==GateKind::H)apply_h(p,w,g.q0);else if(g.kind==GateKind::S)apply_s(p,w,g.q0);else apply_cnot(p,w,g.q0,g.q1);next[p]+=w;}}}
struct Prepared{std::vector<Pauli> keys;std::vector<double> magnitude;std::vector<int8_t> sign;double l1=0;};
Prepared prepare(const Map&m){Prepared p;p.keys.reserve(m.size());p.magnitude.reserve(m.size());p.sign.reserve(m.size());for(const auto&[key,w]:m){double a=std::abs(w);if(a==0)continue;p.keys.push_back(key);p.magnitude.push_back(a);p.sign.push_back(w<0?-1:1);p.l1+=a;}return p;}
void rebuild(Map&m,const Prepared&p,const std::vector<std::uint64_t>&counts,std::size_t K){std::size_t unique=0;for(auto c:counts)if(c)++unique;Map out;out.reserve(unique*2+1);double unit=p.l1/static_cast<double>(K);for(std::size_t i=0;i<counts.size();++i)if(counts[i])out.emplace(p.keys[i],static_cast<double>(p.sign[i])*unit*static_cast<double>(counts[i]));m.swap(out);}
struct LocalStats{double deterministic_fraction=0;};
LocalStats ordinary(Map&m,std::size_t K,std::mt19937_64&rng){auto p=prepare(m);std::vector<std::uint64_t> counts(p.keys.size());std::discrete_distribution<std::size_t> d(p.magnitude.begin(),p.magnitude.end());for(std::size_t s=0;s<K;++s)++counts[d(rng)];rebuild(m,p,counts,K);return {};}
LocalStats residual_multinomial(Map&m,std::size_t K,std::mt19937_64&rng){auto p=prepare(m);std::vector<std::uint64_t> counts(p.keys.size());std::vector<double> residual(p.keys.size());std::uint64_t allocated=0;for(std::size_t i=0;i<p.keys.size();++i){double expected=static_cast<double>(K)*p.magnitude[i]/p.l1;auto base=static_cast<std::uint64_t>(std::floor(expected+1e-12));counts[i]=base;allocated+=base;residual[i]=std::max(0.0,expected-static_cast<double>(base));}if(allocated>K)throw std::runtime_error("invalid residual allocation");std::uint64_t remaining=K-allocated;if(remaining){std::discrete_distribution<std::size_t>d(residual.begin(),residual.end());for(std::uint64_t s=0;s<remaining;++s)++counts[d(rng)];}rebuild(m,p,counts,K);return {static_cast<double>(allocated)/K};}
std::vector<std::uint8_t> dependent_round(std::vector<double>x,std::mt19937_64&rng,std::uint64_t target){constexpr double eps=1e-12;std::uniform_real_distribution<double>u(0,1);std::vector<std::size_t> active;active.reserve(x.size());for(std::size_t i=0;i<x.size();++i){if(x[i]>eps&&x[i]<1-eps)active.push_back(i);else x[i]=x[i]>=0.5?1.0:0.0;}while(active.size()>=2){auto j=active.back();active.pop_back();auto i=active.back();active.pop_back();double xi=x[i],xj=x[j],alpha=std::min(1-xi,xj),beta=std::min(xi,1-xj),den=alpha+beta;if(den<=eps){x[i]=xi>=0.5?1:0;x[j]=xj>=0.5?1:0;}else if(u(rng)<beta/den){x[i]=xi+alpha;x[j]=xj-alpha;}else{x[i]=xi-beta;x[j]=xj+beta;}if(x[i]>eps&&x[i]<1-eps)active.push_back(i);else x[i]=x[i]>=0.5?1:0;if(x[j]>eps&&x[j]<1-eps)active.push_back(j);else x[j]=x[j]>=0.5?1:0;}if(!active.empty()){auto i=active.back();x[i]=x[i]>=0.5?1:0;}std::vector<std::uint8_t>b(x.size());std::uint64_t sum=0;for(std::size_t i=0;i<x.size();++i){b[i]=x[i]>=0.5;sum+=b[i];}if(sum!=target)throw std::runtime_error("dependent rounding population mismatch");return b;}
LocalStats residual_dependent(Map&m,std::size_t K,std::mt19937_64&rng){auto p=prepare(m);std::vector<std::uint64_t>counts(p.keys.size());std::vector<double>residual(p.keys.size());std::uint64_t allocated=0;for(std::size_t i=0;i<p.keys.size();++i){double expected=static_cast<double>(K)*p.magnitude[i]/p.l1;auto base=static_cast<std::uint64_t>(std::floor(expected+1e-12));counts[i]=base;allocated+=base;residual[i]=std::max(0.0,expected-static_cast<double>(base));}if(allocated>K)throw std::runtime_error("invalid dependent allocation");auto remaining=K-allocated;if(remaining){auto b=dependent_round(residual,rng,remaining);for(std::size_t i=0;i<b.size();++i)counts[i]+=b[i];}rebuild(m,p,counts,K);return {static_cast<double>(allocated)/K};}
LocalStats compress(Map&m,std::size_t K,std::mt19937_64&rng,ResamplingMethod method){if(method==ResamplingMethod::OrdinaryMultinomial)return ordinary(m,K,rng);if(method==ResamplingMethod::ResidualMultinomial)return residual_multinomial(m,K,rng);return residual_dependent(m,K,rng);}
double finish(const Map&m){double value=0;for(const auto&[p,w]:m)if(p.x==0)value+=w;return value;}
}
const char* resampling_method_name(ResamplingMethod m){if(m==ResamplingMethod::OrdinaryMultinomial)return "ordinary_multinomial";if(m==ResamplingMethod::ResidualMultinomial)return "residual_multinomial";return "residual_dependent_rounding";}
ResamplingDiagnostics run_resampling_bfs(const Circuit&c,double retained_memory_mb,ResamplingMethod method,std::uint64_t seed){ResamplingDiagnostics d;d.result={c.family,c.name,resampling_method_name(method),"ok"};d.result.reference=c.reference;auto K=std::max<std::size_t>(1,static_cast<std::size_t>(retained_memory_mb*1048576.0/48.0));std::mt19937_64 rng(seed);Map current,next;current[c.observable]=1;int rz_count=0;double deterministic_sum=0;auto start=Clock::now();for(auto it=c.gates.rbegin();it!=c.gates.rend();++it){advance(current,next,*it);current.swap(next);d.result.peak_terms=std::max<std::uint64_t>(d.result.peak_terms,current.size());if(it->kind==GateKind::RZ&&++rz_count==4){if(current.size()>K){auto s=compress(current,K,rng,method);deterministic_sum+=s.deterministic_fraction;++d.resampling_events;}rz_count=0;d.peak_post_terms=std::max<std::uint64_t>(d.peak_post_terms,current.size());}}if(rz_count&&current.size()>K){auto s=compress(current,K,rng,method);deterministic_sum+=s.deterministic_fraction;++d.resampling_events;}d.peak_post_terms=std::max<std::uint64_t>(d.peak_post_terms,current.size());d.average_deterministic_fraction=d.resampling_events?deterministic_sum/d.resampling_events:1.0;d.result.estimate=finish(current);d.result.error=std::abs(d.result.estimate-d.result.reference);d.result.seconds=std::chrono::duration<double>(Clock::now()-start).count();d.result.memory_mb=d.result.peak_terms*48.0/1048576.0;return d;}
}
